### ISSUE TITLE
Validator is not a function

### ISSUE THREAD

**Issue by sarovin** [final-form/react-final-form#98]
Hi, i have this error when update to 2.0.0:
```
Uncaught TypeError: validator is not a function
    at final-form.es.js?2ff5f15:531
    at Array.forEach (<anonymous>).
```
I think that the problem is here =>

>  var errorOrPromise = validator(getIn(state.formState.values, field.name), state.formState.values);

MyForm:
```
import React, { PureComponent } from 'react';
import PropTypes from 'prop-types';
import { Form } from 'react-final-form';
import Message from './comps/message';
import Input from './comps/input';
import Button from '../theme/Button';
import { email } from './validations';

const propTypes = {
  onSubmit: PropTypes.func.isRequired,
  errorForm: PropTypes.shape({
    code: PropTypes.string,
    message: PropTypes.string,
  }).isRequired,
};

class RecoveryPassword extends PureComponent {
  render() {
    const { onSubmit, errorForm } = this.props;

    return (
      <Form
        onSubmit={onSubmit}
        render={({ handleSubmit, pristine, invalid }) => (
          <form className="all-forms" onSubmit={handleSubmit}>
            <div className="contenitore">
              <Input name="email" label="Indirizzo email" type="email" validate={email} />
            </div>

            {errorForm && <Message text={errorForm.message} />}
            <div className="p--s flex-row-j-start-a-center alpha-70 m-l-lg-24">
              Ti invieremo un link per creare la nuova password
            </div>
            <div className="contenitore fluid-container p-a-lg-16 flex--row-j-center-a-center">
              <Button type="submit" disabled={pristine || invalid} label="Recupera" />
            </div>
          </form>
        )}
      />
    );
  }
}

```

### What's your environment?

react: 16.2.0
react-final-form: 2.0.0
node: 8.9.3

**Comment by Skaronator** [comment]
Thats not how you setup a Field. You must use the Field element from final form.

```import { Field } from 'react-final-form';```

And then use it like this:
```
<Field
    name="password"
    type="password"
    label="Password"
    component={CustomTextField}
    disabled={submitting}
  />
```

**Comment by sarovin** [comment]
Yes @Skaronator.
This is my Input Component:
```
class Input extends PureComponent {
  constructor(props) {
    super(props);

    this.handleOnChange = this.handleOnChange.bind(this);
  }

  handleOnChange(e) {
    const { onChange, input } = this.props;

    input.onChange(e.target.value);
    if (onChange) onChange({ [input.name]: e.target.value });
  }

  render() {
    const {
      input, meta, label, type, step,
    } = this.props;

    return (
      <label htmlFor={input.name}>
        {label}
        <input
          {...input}
          step={step}
          onChange={this.handleOnChange}
          className="text-field-default w-input"
          type={type}
        />
        {meta.error &&
          meta.touched && (
            <div>
              {meta.error}
            </div>
          )}
      </label>
    );
  }
}

```

**Comment by erikras** [comment]
You're not using the `Field` component anywhere.

This:
```jsx
<Input name="email" label="Indirizzo email" type="email" validate={email} />
```
should be:
```jsx
<Field name="email" component={Input} label="Indirizzo email" type="email" validate={email} />
//                  ^^^^^^^^^^^^^^^^^
```
