### ISSUE TITLE
NPM wrong version of ts-essentials being called in

### ISSUE THREAD

**Issue by kevmojay** [final-form/react-final-form#599]
### Are you submitting a **bug report** or a **feature request**?

bug report

### What is the current behavior?

If I install the newest version via npm, my build job breaks because I get.

```
node_modules/ts-essentials/dist/types.d.ts:5:13 - error TS2322: Type 'K' is not assignable to type 'string'.
  Type 'string | number' is not assignable to type 'string'.
    Type 'number' is not assignable to type 'string'.

5     [key in K]: T;
```

### What is the expected behavior?
Build job succeeds

### What's your environment?

react-final-form: 6.3.0
typescript:3.5.3

### Other information
I was able to track it down to what seems like the dependency version that is in NPM for ts-essentials is 2.0.8 but your master branch in this repo is 3.0.2.

I had my package.json install from github instead of NPM and that worked.

The screenshot shows that the installed package has latest version of react-final-form but an old version of ts-essentials

![Screen Shot 2019-08-20 at 2 23 14 PM](https://user-images.githubusercontent.com/11466536/63386217-61175180-c357-11e9-8673-6d05a59be08f.png)

**Comment by lookfirst** [comment]
I'm super curious if this project is really being maintained anymore. 7 days to update a simple dependency. =( So sad.

For the maintainers, this really affects new people who come into your project. I just discovered both this project and ts-essentials... started using it and then now I find this issue...

**Comment by kgregory** [comment]
Looks to be updated August 19th, but hasn't shipped.

Ran into this after bumping `ts-essentials` to v3 in my project.

**Comment by tsengkasing** [comment]
Could someone please tell me that when will this be shipped?

**Comment by kgregory** [comment]
@tsengkasing A new release has been cut 3 hours ago.  Good timing!

**Comment by kgregory** [comment]
@erikras I think this one may have been closed with the latest release.

**Comment by erikras** [comment]
> I'm super curious if this project is really being maintained anymore. 7 days to update a simple dependency. =( So sad.

@lookfirst, the sole maintainer has a full time job, a family, and, in August, was writing [a brand new, responsive, docs website](https://final-form.org/react) for this project, and in September and October was speaking at conferences to promote the project. Sorry to sadden you.

**Comment by lookfirst** [comment]
Yep, I also have a more than full time job (I am an expat developer too), a life, a few popular open source projects and I know how to delegate responsibility to others so they can helpfully click buttons for me. ;-)

I appreciate the comment though!

**Comment by kgregory** [comment]
@erikras I appreciate your efforts and have only a slight idea of what a thankless job it must be at times.  Thank you for your work.

**Comment by lookfirst** [comment]
@kgregory It isn't thankless. I and others have thanked him tons of times. He's built an amazing project. It is all super appreciated. But we are all hard workers here contributing to open source... I don't understand the special treatment. If someone calls me out, I just try to improve my game, work more efficient, ask for help... not get defensive or sad about it. It doesn't have to be looked at as a 'thankless' thing... if you put stuff out there and work hard to get lots of users... find ways to get the help to support yourself.

**Comment by kgregory** [comment]
@lookfirst I'm sure you appreciate his work, but there's a discouraging tone to your comments in this issue.  I think we should conclude our discussion as it isn't particularly relevant to the issue.  If you'd like to continue it elsewhere, let me know.
